import { createApp } from "vue";
import App from "./App.vue";
import register from "./register";
import store from "./store";
import router from "./router";
const app = createApp(App);
app.use(register);
app.use(store);
app.use(router);
app.mount("#app");
